### ISSUE TITLE
Can this package automatically reorder with animation when data source is changed?

### ISSUE THREAD

**Issue by aytunch** [Mindinventory/flutter_draggable_gridview#1]
In my app, I don't need the user to reorder the contents but they are done when some filters are enabled.

Use case:

Grids show cars.
When user presses red color, I want to show only the red colored cars
And I want this filtering to happen in an animated way.
So there might be several cars that are removed from different places of the cars array.
When the filter is removed, all cars should be added in place with ordering animation.

Can I use this package for this need?

**Comment by sahilmind** [comment]
There is no provision for order now, considering as enhancement. Thanks @aytunch
