### ISSUE TITLE
Example request: Using ScrollController

### ISSUE THREAD

**Issue by danielpjr** [Mindinventory/flutter_draggable_gridview#14]
I did several tests but it didn't work scrolling the screen

**Comment by sahilmind** [comment]
@danielpjr I apologise for the issue. I think you are trying to use ScrollController with DraggableGridViewBuilder and it is not working as expected. Correct me if I am wrong.

**Comment by sahilmind** [comment]
@danielpjr  added an example using **ScrollController** in **flutter_draggable_gridview**: **0.0.7** please have a look.
I am happy to help you if required.
Thanks!
