### ISSUE TITLE
Does this package animate reorder using code

### ISSUE THREAD

**Issue by zezo357** [Mindinventory/flutter_draggable_gridview#17]
For my use case the data changes from api so I - need to animate the changes, does this package offer that?

**Comment by sahilmind** [comment]
@zezo357 When your Dataset change, pass that data to the DraggableGridViewBuilder and it will update the gridview widget according to your data. Let me know if any other help you want. 
I am happy to help you.
Thanks

**Comment by zezo357** [comment]
My problem is the animation, so will DraggableGridViewBuilder animate the changes? 
Thank you ❤️

**Comment by deep-mindinventory** [comment]
@zezo357 currently, this package is not providing this feature. Users can drag items manually for changing the position.
