### ISSUE TITLE
Your test example fails to drag image to new position with version 0.0.3

### ISSUE THREAD

**Issue by wreyford** [Mindinventory/flutter_draggable_gridview#3]
I was using flutter_draggable_gridview 0.0.1, before you refactored your code without any issues.

After upgrading to 0.0.3 and you drag the image, it doesn't move the other images to make place for the dragged image on the gridview, as it did in the past, but the gird just remains static, and when you drop the image, it returns to its original place.

I tested using your example code from this repo, and exactly the same thing happens when I run your example code.

Can you please look into this problem.

Thx

**Comment by wreyford** [comment]
Please can you look into this, as makes your package unusable.

**Comment by sahilmind** [comment]
@wreyford Sure, I will check and update ASAP.

**Comment by wreyford** [comment]
Hi @sahilmind, hope you are well.
Were you able to have a look yet?

**Comment by danielle-h** [comment]
I have the same problem, is there a solution?

**Comment by wreyford** [comment]
Hello @sahilmind, issue reported 16 Jan 2022. Is there any possibility you give it the required attention. As is, your package no longer works. Please indicate if you are serious about this package going forward.

**Comment by sahilmind** [comment]
@wreyford Sorry for the delay in responding, I am very happy to fixed this issue for you. V0.0.4 will address your problem. Do not hesitate to contact us if you have any additional feedback.

**Comment by wreyford** [comment]
Thx @sahilmind . Really appreciate.
