### ISSUE TITLE
There is a bug in darg_target_grid.dart

### ISSUE THREAD

**Issue by buptwsg** [Mindinventory/flutter_draggable_gridview#5]
version: 0.0.4

file drag_target_grid.dart, line 84:
DraggableGridItem(child: EmptyItem(), isDraggable: true);

should be :

DraggableGridItem(child: widget.placeHolder ?? EmptyItem(), isDraggable: true);

Could you please fix this ASAP and release a new version 0.0.5? Otherwise I have to use source code to integrate into my project. Thanks a lot!

**Comment by abrarmalekji345** [comment]
This is fixed now
