### ISSUE TITLE
Feature request: provide 'isDragging' details to DraggableGridItem

### ISSUE THREAD

**Issue by lukepighetti** [Mindinventory/flutter_draggable_gridview#9]
DraggableGridItem currently has no way to know if it's being dragged. Instead of a `Widget child` argument, a builder argument with `(BuildContext context, bool isDragging)` could be provided

**Comment by sahilmind** [comment]
@lukepighetti  added a feature for **isDragging** flag to **DraggableGridItem** in **flutter_draggable_gridview**: **0.0.7** please have a look.
I am happy to help you if required.
Thanks!
